### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by appi1** [stefschin/BrewPiLess-32-PCB#1]
hi 
can you please release the PCB for brewpiless.
txh remo

**Comment by stefschin** [comment]
Hi, sorry man, I was my other priorities. I'm just finishing board routing but I have a doubt about ESP32 devkit boards, I found that cheaper ones have 30, 36 and 38 pins. I can't find real dimensions of 36 version and I'm making a generic board for this 3 models.
Can you tell which one do you have? 
best

**Comment by appi1** [comment]
Hello
Thank you for your answer. For me it doesn't matter which ESP32 board is used on the PCB. it is easier for me to order the appropriate board instead of developing my own PCB. I'm looking forward to the PCB. I often work with the following board: https://www.az-delivery.de/products/esp32-lolin-lolin32

**Comment by stefschin** [comment]
Hi Remo,
I've published last night board on PCBWay Projects. 
https://www.pcbway.com/project/shareproject/BrewPiLess_ESP32_Rev_00.html
Very cheap 

You can use this 38 pin board:
https://www.az-delivery.de/products/esp32-dev-kit-c-unverlotet
other 30 pin:
https://www.amazon.de/Espressif-Development-Bluetooth-WROOM32-NodeMCU/dp/B07K68RQTS

thanks for your patience

**Comment by appi1** [comment]
hi Stephan
just ordered, the PCB's arrive in 5 days.....  a wunderfull world, thank you very much.
if the PCB arrive i will give you a feedback

**Comment by appi1** [comment]
hey Stephan
the pins for my ESP32 ( Wemos 32 lite ) are a bit far apart. but with some soldering tricks it works very well. I can only do the final test in the live environment.
Thanks again for the PCB design.

**Comment by stefschin** [comment]
Your welcome! I was thinking to do another version for Wemos 32, ESP32 Lolin and maybe ESP8266 too
Send a photo to see how you have adapted. Thanks for your feedback!

**Comment by stefschin** [comment]
First version released
