### ISSUE TITLE
BOM?

### ISSUE THREAD

**Issue by Naesstrom** [stefschin/BrewPiLess-32-PCB#2]
Would love a hands down bill of materials for this. Just got my 5 PCB's that I ordered!
The smaller ones look like 2.54mm (0.1")spacing but are the larger ones 5.08mm (0.2") or 3.96mm (0.156")?

**Comment by stefschin** [comment]
Hi Erik, sorry that I haven't upload a BOM, I will make it later, I'm not with my notebook.
Yes, smaller ones are 2.54 mm pitch, like Arduino connections and larger ones are terminal blocks with 5.08 mm pitch. thanks for your support and give me a feedback when you test boards

**Comment by palmtreefrb** [comment]
I would also appreciate a BOM as I'm currently waiting for a review and reply of my order on PCBWay.

**Comment by Naesstrom** [comment]
I started writing down some that I found, not sure about all the parts, some might not be needed based on what configuration you are running with!
@stefschin if I populate r4 and r5 for the analog sensor (P3) do I still need to use a ADS1115 or is that only needed if I want to use P11?

Resistors:
r1: 4.7k (1-wire)
r2: 4.7k
r3: 4.7k
r4: 10k (adc)
r5: 20k (adc)
r6: 10k (buzzer)
_So r4 & r5 is only to make a voltage divider for example a pressure sensor. r6 is if using a buzzer with a mosfet_
Not sure about r2 and r3, seems to be for some extra i2c?

Buzzer: 5v, 12mm outer diameter. Leg distance 7.6mm
1x 2N7000 or 2N7002 Mosfet transistor channel N

3x screw terminals 5.08mm spacing, 3-pin (p1, p2, p3)
1x screw terminal 5.08mm spacing 1-pin (J1)

1x pin header, 2.54mm spacing, 1x2 pin (jp1)
1x pin header, 2.54mm spacing, 1x6 pin (p5)
1x pin header, 2.54mm spacing, 1x5 pin (p6)
1x pin header, 2.54mm spacing, 1x3 pin (p7)
3x pin header, 2.54mm spacing, 1x4 pin (p8, p9, p11)
1x IDC male 10-pin (p10)

**Comment by palmtreefrb** [comment]
> I started writing down some that I found, not sure about all the parts, some might not be needed based on what configuration you are running with!
> @stefschin if I populate r4 and r5 for the analog sensor (P3) do I still need to use a ADS1115 or is that only needed if I want to use P11?
> 
> Resistors:
> r1: 4.7k (1-wire)
> r2: 4.7k
> r3: 4.7k
> r4: 10k (adc)
> r5: 20k (adc)
> r6: 10k (buzzer)
> _So r4 & r5 is only to make a voltage divider for example a pressure sensor. r6 is if using a buzzer with a mosfet_
> Not sure about r2 and r3, seems to be for some extra i2c?
> 
> Buzzer: 5v, 12mm outer diameter. Leg distance 7.6mm
> 1x 2N7000 or 2N7002 Mosfet transistor channel N
> 
> 3x screw terminals 5.08mm spacing, 3-pin (p1, p2, p3)
> 1x screw terminal 5.08mm spacing 1-pin (J1)
> 
> 1x pin header, 2.54mm spacing, 1x2 pin (jp1)
> 1x pin header, 2.54mm spacing, 1x6 pin (p5)
> 1x pin header, 2.54mm spacing, 1x5 pin (p6)
> 1x pin header, 2.54mm spacing, 1x3 pin (p7)
> 3x pin header, 2.54mm spacing, 1x4 pin (p8, p9, p11)
> 1x IDC male 10-pin (p10)

...thanks!!!

**Comment by stefschin** [comment]
> I started writing down some that I found, not sure about all the parts, some might not be needed based on what configuration you are running with!
> @stefschin if I populate r4 and r5 for the analog sensor (P3) do I still need to use a ADS1115 or is that only needed if I want to use P11?
> 
> Resistors:
> r1: 4.7k (1-wire)
> r2: 4.7k
> r3: 4.7k
> r4: 10k (adc)
> r5: 20k (adc)
> r6: 10k (buzzer)
> _So r4 & r5 is only to make a voltage divider for example a pressure sensor. r6 is if using a buzzer with a mosfet_
> Not sure about r2 and r3, seems to be for some extra i2c?
> 
> Buzzer: 5v, 12mm outer diameter. Leg distance 7.6mm
> 1x 2N7000 or 2N7002 Mosfet transistor channel N
> 
> 3x screw terminals 5.08mm spacing, 3-pin (p1, p2, p3)
> 1x screw terminal 5.08mm spacing 1-pin (J1)
> 
> 1x pin header, 2.54mm spacing, 1x2 pin (jp1)
> 1x pin header, 2.54mm spacing, 1x6 pin (p5)
> 1x pin header, 2.54mm spacing, 1x5 pin (p6)
> 1x pin header, 2.54mm spacing, 1x3 pin (p7)
> 3x pin header, 2.54mm spacing, 1x4 pin (p8, p9, p11)
> 1x IDC male 10-pin (p10)

Sorry for delay, we have new restrictions for Covid here and my mother is sick...

Thanks to answer to other guys with this BOM, it's ok just J1 it's 2-pin screw terminal 5.08mm spacing, I'making a BOM to add to the project anyway.

As you say, R2 and R3 are Pull ups for I2C if they are note populated in your I2C hardware, what's not usual.

R4 and R5 are for setting a Voltage divider to supply ADC input of ESP-32.
Attenuation calculation is AT=(R4+R5)/R5, it's better to use resistores in order of 10k until 500k. 
For example if you use R4=10k and R5=20k AT=30k/20k=1.5 and if your max input is 5V, your ADC input will be: 5V/1.5=3.3V
You can connect one analog sensor without ADS1115 or other ADC converter directly to this input, just check max voltages.

But if you have more than one analog sensor or want to use ADS1115, it has I2C communication, so I would connect it to P11 and make a short between 2 and 3 of JP2 to supply board with 3.3V.

Any other doubt fill free to ask. Thanks for testing this board!

**Comment by stefschin** [comment]
BOM in pdf and xlsx added

**Comment by stefschin** [comment]
BOM released
