### ISSUE TITLE
Rotary Switch

### ISSUE THREAD

**Issue by shingle01** [stefschin/BrewPiLess-32-PCB#4]
Really liking the BrewPiLess-32-PCB, in the early stages on setup.  I've built the OLED binary.

![image](https://user-images.githubusercontent.com/43157345/132164414-38d41be5-a3cb-4956-93f9-02b3e545e665.png)

I haven't had much luck with the rotary switch.  I realize web interface is easier but I like the idea of a fall back.

I thought the KY-040 would be a safe bet but it would appear to require 5V instead of the reserved 3.3V output on the PCB.  Powering the KY-040 with 5V doesn't work around the issue.

What rotary switch do you recommend?

Edit:  Perhaps rotary is not a default option in the code...  I will look into this.

**Comment by shingle01** [comment]
I'm reading conflicting information.  e.g. rotary not supported with oled etc.  It seems the developer has pretty much dropped support for rotary encoders?

**Comment by shingle01** [comment]
Oh I see the problem, the boards GPIOs don't match up.  Had to plug rotary push into GPIO25 to get working:

![image](https://user-images.githubusercontent.com/43157345/132186192-d941c3af-c58b-4e4d-a131-ed61c295122b.png)

**Comment by Naesstrom** [comment]
Thanks for the heads up, still have my pcb on the bench but slowly getting there!

**Comment by stefschin** [comment]
Hi! Nice to know and see board assembled and working! 
Yes, you are right, default firmware has rotary push on pin 25, I have to make a new bin with push on pin 27 to comply with this board but I didin't have the PCB myself to test it. Now I'm making a shield for CraftBeerPi so after that I order this two board for me. 
If you want, you can change Config.h:
#define rotarySwitchPin 25 to 27 and compile again

Or use it like you do it
Or wait until I make special bins for this board. Cheers!

**Comment by shingle01** [comment]
Yep, just need to swap these values in config.h, all other pins look good.

#define actuatorPin4  27
#define rotarySwitchPin 25

to 

#define actuatorPin4  25
#define rotarySwitchPin 27

@stefschin, DM your address, and I'll send you a couple of my PCBs (5 board minimum order).  

Edit:  Looking forward to see your shield for CraftBeerPi

**Comment by stefschin** [comment]
Yes @shingle01 that's right, thanks

I don't know how to send you my address, Github doesn't have a DM but my email is same as github user @gmail.com.
Cheers!
