### ISSUE TITLE
Buzzer polarity

### ISSUE THREAD

**Issue by shingle01** [stefschin/BrewPiLess-32-PCB#5]
I believe the buzzer according to the images on pcbway is the wrong polarity.

**Comment by stefschin** [comment]
Hi! Yes, you are right! 3D is in the wrong way, positive is on the right side of the board, I forgot to indicate it on silkscreen. Thanks for feedback, my email is same as my user name with google mail.
Best

**Comment by stefschin** [comment]
PCB Information Updated
