### ISSUE TITLE
A few observations since using the board

### ISSUE THREAD

**Issue by shingle01** [stefschin/BrewPiLess-32-PCB#7]
- I've been using the I/O extra header for DHT22 humidity sensors.  The header has a 3.3V supply.  Unfortunately, the DHT is not stable on 3.3V with cable length >1m, cable length required to reach chamber.  I will probably look to optimize cable length or move DHT sensors to 4xRelay header w/5V supply.  This would be a shame as the 4 x relay header could be used for auto-spunding, humidity control and chamber light etc.
- Onboard support for a ADS1115 breakout board. I don't have issues with the onboard ADC but developer notes results are non-linear and do require calibration.  ADS1115 would be recommended if auto-spunding.
- _Header for BMP280 (Chamber Humidity sensor alternative) supported in 4.2_

EDIT: In addition to the I/O extra header I'd probably just add an additional 4-pin header with 5V.  Chamber / room humidity.

EDIT 2:  You already have a I2C Header for BMP280.

**Comment by shingle01** [comment]
Nevermind.  ADS1115 or BMP280 can use the I2C header.  I'll move the relays to the 4 x relay header and use the 2 x relay header for humidity sensors.  Problem solved.

**Comment by stefschin** [comment]
Good work @shingle01, that's why I left I-the I2C Header, for an extra module or tests. But isn't a bad idea to let a space to solder a ADS115 module. It's ok too, to add jumpers to VCC pins so you can select 3V3 or 5V. Thanks for your testing and feedback! I have so much work that I couldn't buy and build my own yet. My next PCB will be a CraftBeerPi Shield PCB...stay tuned. ;)

**Comment by shingle01** [comment]
Looking forward to see what you come up with next.  In my opinion, given I
only brew in a single vessel, an esp32 project board for brewmaniac would
be better. Craftbeerpi development has been slow.

**Comment by stefschin** [comment]
Craftbeerpi 4 is working well thanks to Alexander: https://github.com/avollkopf/craftbeerpi4
and it has a online manual https://openbrewing.gitbook.io/craftbeerpi4_support/
But you are right, maybe for just a single vessel it's too much, Brewmaniac is working with ESP32?

**Comment by shingle01** [comment]
There is a BrewManiacEx.050.esp32.bin binary available so I assume so.  

There is a BrewManiacEx project board for the esp8266 which looks interesting but I figured there is a gap for those looking to use an esp32.

Nice, I'll check out the craftbeerpi fork.

**Comment by stefschin** [comment]
I will check-it! Thanks shingle01!
